modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "thingymabobs"
version = "${mod_version}"
displayName = "Thingymabobs"
description = '''
Adds a few more things to PowerGrid!
'''

[[dependencies.thingymabobs]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.thingymabobs]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.thingymabobs]]
modId = "powergrid"
type = "required"
versionRange = "[0.5.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thingymabobs]]
modId = "create"
type = "required"
versionRange = "[6.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thingymabobs]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="META-INF/thingymabobs.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"